---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx-internal"
  name: grafana
  namespace: {{ .namespace }}
spec:
  tls:
  - secretName: tls-secret-grafana
    hosts:
    #- grafana.internal.${ENVIRONMENT}.${BASE_DOMAIN_NAME}
    - grafana.demo.devops.bot
  rules:
  - host: grafana.demo.devops.bot
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 3000
