---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx-internal"
  name: grafana
  namespace: {{ .namespace }}
spec:
  tls:
  - secretName: tls-secret-grafana
    hosts:
    - {{ .url_hostname }}
  rules:
  - host: {{ .url_hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 3000
