---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: {{ .namespace }}
spec:
  selector:
    app: grafana
  ports:
  - name: grafana
    protocol: TCP
    port: 3000
