---
apiVersion: v1
kind: ConfigMap
metadata:
  name: es-configs
data:
  elasticsearch.yml: |-
    cluster.name: "docker-cluster"
    network.host: 0.0.0.0

    # minimum_master_nodes need to be explicitly set when bound on a public IP
    # set to 1 to allow single node clusters
    # Details: https://github.com/elastic/elasticsearch/pull/17288
    #discovery.zen.minimum_master_nodes: 1
    discovery.zen.ping.unicast.hosts: elasticsearch-logging-v1-0.elasticsearch-logging

    # Disabling x-pack because this needs a license and will expire in 30 days if
    # left enabled.
    xpack.security.enabled: false
