apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: spinnaker-spinnaker
  namespace: spinnaker
  labels:
    app: spinnaker-spinnaker
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: spinnaker
