---
apiVersion: v1
kind: Service
metadata:
  name: ingress-external
  namespace: infrastructure
  annotations:
    prometheus.io/port: "10253"
    prometheus.io/scrape: "true"

spec:
  type: LoadBalancer
  selector:
    app: ingress-controller-external
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
