---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-2
spec:
  selector:
    istio: ingressgateway-2
  servers:

  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
