---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: node-exporter
  name: node-exporter
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 9100
  selector:
    app: node-exporter
  type: ClusterIP
