apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-saas-efs-us-east-1-demo
spec:
  storageClassName: nfs-class
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs-203f2069.efs.us-east-1.amazonaws.com
    path: "/"
