apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-prometheus
spec:
  storageClassName: nfs-class
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs-89373dc0.efs.us-east-1.amazonaws.com
    path: "/"
