- name: cluster-health.rules
  rules:
  - alert: ExcessivePodsInPendingState
    expr: count(kube_pod_status_phase{phase="Pending"} == 1) > 40
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'This can mean that there is not enough capacity in the cluster.  Current
        value: {{ $value }}'
      summary: The number of pods in a pending state is over 10.  This can also mean a node might be unavailable.
