- name: cpu.rules
  rules:
  - alert: NodeLoadAverage5minutes
    expr: node_load5 > count(node_cpu{mode="idle"}) WITHOUT (cpu, mode) * 5
    for: 30m
    labels:
      severity: page
    annotations:
      description: '{{ $labels.instance }} 1m load average is: {{ $value }}).'
      summary: Node 1 minute load average is high
  - alert: NodeLoadAverage15minutes
    expr: node_load15 > count(node_cpu{mode="idle"}) WITHOUT (cpu, mode) * 5
    for: 60m
    labels:
      severity: page
    annotations:
      description: '{{ $labels.instance }} 15m load average is: {{ $value }}).'
      summary: Node 15 minute load average is high
  # - alert: HighCPU
  #   expr: 100 - (avg(irate(node_cpu{job="node-exporter",mode="idle"}[5m])) BY (instance)
  #     * 100) > 75
  #   for: 10m
  #   labels:
  #     severity: warning
  #   annotations:
  #     description: '{{ $labels.kubernetes_io_hostname }} has CPU usage above 75% for
  #       over 10m (current value is: {{ $value }}%).'
  #     summary: CPU Usage is over 75%
  # - alert: HighCPU
  #   expr: 100 - (avg(irate(node_cpu{job="node-exporter",mode="idle"}[10m])) BY (instance)
  #     * 100) > 90
  #   for: 10m
  #   labels:
  #     severity: critical
  #   annotations:
  #     description: '{{ $labels.kubernetes_io_hostname }} has CPU usage above 90% for
  #       over 10m (current value is: {{ $value }}%).'
  #     summary: CPU Usage is over 90%
