- name: kube-node-status.rules
  rules:
  - alert: KubeNodeStatusOutOfDisk
    expr: kube_node_status_out_of_disk{condition="true"} > 0
    for: 1m
    labels:
      severity: page
    annotations:
      description: This kube node status is reporting that it is out of disk space
      summary: 'Kube node is reporting out of disk space: {{$labels.node}}'
  - alert: KubeNodeStatusDiskPressure
    expr: kube_node_status_disk_pressure{condition="true"} > 0
    for: 1m
    labels:
      severity: page
    annotations:
      description: Pressure exists on the disk size – that is, if the disk capacity
        is low
      summary: 'Kube node is reporting disk pressure is high: {{$labels.node}}'
  - alert: KubeNodeStatusMemoryPressure
    expr: kube_node_status_memory_pressure{condition="true"} > 0
    for: 1m
    labels:
      severity: page
    annotations:
      description: Pressure exists on the node memory – that is, if the node memory
        is low
      summary: 'Kube node is reporting memory pressure is high: {{$labels.node}}'
