- name: kube-apiserver.rules
  rules:
  - alert: K8SApiserverDown
    expr: absent(up{job="kubernetes"} == 1)
    for: 5m
    labels:
      severity: critical
    annotations:
      description: Prometheus failed to scrape Kube API server(s), or all API servers
        have disappeared from service discovery.
      summary: API server unreachable
