- name: kube.state.metric.pod.container.status.terminated.reason
  rules:
  - alert: KubeStateContainerStatusTerminatedReasonOOMKilled
    expr: kube_pod_container_status_terminated_reason{reason="OOMKilled"} == 1
    for: 1m
    labels:
      severity: page
    annotations:
      description: '{{ $labels.pod }} was OOMKilled. Value: {{ $value }}'
      summary: Pod was killed for using more than the memory limits set
