apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /alertmanager/metrics
    prometheus.io/port: "9093"
    prometheus.io/scrape: "true"
  labels:
    app: alertmanager
  name: alertmanager
spec:
  ports:
  - name: alertmanager
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    app: alertmanager
  sessionAffinity: None
