apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: butterfly-2
  annotations:
    # Use the classic nginx load balancer with the classic ELB
    kubernetes.io/ingress.class: "nginx"
    # Setup Let's Encrypt Certificates
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"

spec:
  tls:
  - hosts:
    - butterfly-demo2.demo.devops.bot
    secretName: butterfly-2
  rules:
  - host: butterfly-demo2.demo.devops.bot
    http:
      paths:
      - path: /
        backend:
          serviceName: butterfly-2
          servicePort: 57575
