---
apiVersion: v1
kind: Service
metadata:
  name: ingress-internal
  namespace: infrastructure
  annotations:
    prometheus.io/port: "10253"
    prometheus.io/scrape: "true"
    # https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balancing#config
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 10.0.0.0/8
  selector:
    app: ingress-controller-internal
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
